# Generated by Django 5.1.15 on 2026-10-09 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Prism Pulse", max_length=100)),
                (
                    "role",
                    models.CharField(
                        default="Photographer · Cinematographer · Drone Operator",
                        max_length=255,
                    ),
                ),
                (
                    "portrait_src",
                    models.URLField(
                        default="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1600&q=85",
                        max_length=500,
                    ),
                ),
                (
                    "portrait_alt",
                    models.CharField(
                        default="Studio portrait of Prism Pulse visual director in warm chiaroscuro ambient light",
                        max_length=255,
                    ),
                ),
                (
                    "portrait_caption",
                    models.CharField(
                        default="Studio Archive · Portrait by Natural Window Light · 2025",
                        max_length=255,
                    ),
                ),
                (
                    "intro_headline",
                    models.CharField(
                        default="Finding permanence in fleeting light, deliberate motion, and vast horizons.",
                        max_length=255,
                    ),
                ),
                (
                    "intro_paragraphs",
                    models.JSONField(
                        default=list, help_text="List of intro paragraphs as strings"
                    ),
                ),
                (
                    "philosophy_title",
                    models.CharField(default="Creative Philosophy", max_length=100),
                ),
                (
                    "philosophy_statement",
                    models.TextField(
                        default="We do not manufacture cinema; we cultivate patience until reality reveals its own poetry."
                    ),
                ),
                (
                    "skills_title",
                    models.CharField(
                        default="Core Disciplines & Technical Craft", max_length=100
                    ),
                ),
                (
                    "equipment_title",
                    models.CharField(
                        default="Selected Production Equipment", max_length=100
                    ),
                ),
                (
                    "equipment_description",
                    models.TextField(
                        default="A dedicated inventory of cinema optics, medium format sensor platforms, and commercial drone systems."
                    ),
                ),
            ],
            options={
                "verbose_name": "About Profile",
                "verbose_name_plural": "About Profiles",
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Discipline identifier (e.g. photography, cinematography, drone)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tagline", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("hero_image_url", models.URLField(max_length=500)),
                (
                    "hero_image_alt",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Discipline",
                "verbose_name_plural": "Disciplines",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceGroup",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Discipline slug (e.g. photography, cinematography, drone)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Display number, e.g. 01", max_length=10
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        help_text="Discipline title, e.g. Photography", max_length=100
                    ),
                ),
                ("tagline", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("hero_image_url", models.URLField(max_length=500)),
                ("image_alt", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service Group",
                "verbose_name_plural": "Service Groups",
                "ordering": ["sort_order", "number"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Prism Pulse", max_length=100)),
                (
                    "tagline",
                    models.CharField(
                        default="Photographer · Cinematographer · Drone Operator",
                        max_length=255,
                    ),
                ),
                ("disciplines", models.JSONField(default=list)),
                (
                    "location",
                    models.CharField(default="Available Worldwide", max_length=255),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="commissions@prismpulse-visuals.com", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+1 (415) 890-4421", max_length=50),
                ),
                (
                    "representation",
                    models.CharField(
                        default="Direct Artist Representation · Available Worldwide",
                        max_length=255,
                    ),
                ),
                (
                    "operating_hours",
                    models.CharField(
                        default="Studio Office: Monday – Friday · 09:00 – 18:00 CET",
                        max_length=255,
                    ),
                ),
                (
                    "response_note",
                    models.TextField(
                        default="All inquiries are personally reviewed within 24 to 48 hours. Confidential project NDAs supported upon request."
                    ),
                ),
                (
                    "contact_side_image_url",
                    models.URLField(
                        blank=True,
                        default="https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1600&q=85",
                        max_length=500,
                    ),
                ),
                (
                    "contact_side_image_alt",
                    models.CharField(
                        blank=True,
                        default="Sunlight filtering through forest canopy into deep atmospheric shadows",
                        max_length=255,
                    ),
                ),
                (
                    "contact_side_image_caption",
                    models.CharField(
                        blank=True,
                        default="Field Production Notes · Light & Environmental Scouting · 2025",
                        max_length=255,
                    ),
                ),
                (
                    "home_display_name",
                    models.CharField(default="Prism Pulse", max_length=100),
                ),
                (
                    "home_role_tag",
                    models.CharField(
                        default="PHOTOGRAPHER / DRONE PILOT", max_length=100
                    ),
                ),
                (
                    "home_coordinates",
                    models.CharField(
                        default="23.8103° N, 90.4125° E — DHAKA", max_length=100
                    ),
                ),
                (
                    "home_reel_tag",
                    models.CharField(default="REEL 35MM / 4K", max_length=100),
                ),
                (
                    "home_hero_headline",
                    models.CharField(
                        default="Visual Stories Across Light & Motion", max_length=255
                    ),
                ),
                (
                    "home_hero_intro",
                    models.TextField(
                        default="Dedicated to capturing evocative moments through high-altitude aerial perspectives, intentional 35mm composition, and atmospheric cinematography."
                    ),
                ),
                (
                    "home_hero_image_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "home_hero_image_alt",
                    models.CharField(
                        default="Prism Pulse operating drone outdoors in natural landscape",
                        max_length=255,
                    ),
                ),
                (
                    "home_hero_caption",
                    models.CharField(
                        default="Field Journal 08 · Aerial Scout · 2025", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text="List of equipment gear items as strings",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_categories",
                        to="content.aboutprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Category",
                "verbose_name_plural": "Equipment Categories",
                "ordering": ["sort_order", "group_name"],
            },
        ),
        migrations.CreateModel(
            name="JournalPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Travel Experiences", "Travel Experiences"),
                            ("Gear & Optics", "Gear & Optics"),
                            ("Photography Stories", "Photography Stories"),
                            ("Filmmaking Stories", "Filmmaking Stories"),
                            ("Behind the Scenes", "Behind the Scenes"),
                            ("Field Notes", "Field Notes"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "published_date",
                    models.CharField(
                        help_text="Formatted date string matching UI, e.g. February 14, 2025",
                        max_length=50,
                    ),
                ),
                (
                    "read_time",
                    models.CharField(help_text="e.g. 5 min read", max_length=50),
                ),
                ("excerpt", models.TextField()),
                ("cover_image_url", models.URLField(max_length=500)),
                ("cover_alt", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("intro_paragraph", models.TextField()),
                ("quote", models.TextField(blank=True, default="")),
                (
                    "quote_author",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "body_paragraphs",
                    models.JSONField(
                        default=list,
                        help_text="List of article body paragraphs as strings",
                    ),
                ),
                ("technical_note", models.TextField(blank=True, default="")),
                ("takeaway", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Journal Post",
                "verbose_name_plural": "Journal Posts",
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_published"],
                        name="content_jou_categor_85b848_idx",
                    ),
                    models.Index(fields=["slug"], name="content_jou_slug_4924b9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PhilosophyTenet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenets",
                        to="content.aboutprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Philosophy Tenet",
                "verbose_name_plural": "Philosophy Tenets",
                "ordering": ["sort_order", "number"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="content.discipline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Category",
                "verbose_name_plural": "Portfolio Categories",
                "ordering": ["sort_order", "name"],
                "unique_together": {("discipline", "name"), ("discipline", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ProfessionalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_notes",
                        to="content.aboutprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional Note",
                "verbose_name_plural": "Professional Notes",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Reel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Travel", "Travel"),
                            ("Behind the Scenes", "Behind the Scenes"),
                            ("Events", "Events"),
                            ("Cinematic Shorts", "Cinematic Shorts"),
                            ("Creative Projects", "Creative Projects"),
                        ],
                        max_length=100,
                    ),
                ),
                ("poster_url", models.URLField(max_length=500)),
                (
                    "youtube_video_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="11-character YouTube video ID (e.g. dQw4w9WgXcQ)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 11-character YouTube video ID.",
                                regex="^[A-Za-z0-9_-]{11}$",
                            )
                        ],
                    ),
                ),
                (
                    "video_src",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Direct MP4 video URL for HTML5 player transition",
                        max_length=500,
                    ),
                ),
                ("duration", models.CharField(help_text="e.g. 0:45", max_length=20)),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[("vertical", "Vertical"), ("cinematic", "Cinematic")],
                        default="vertical",
                        max_length=20,
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=255)),
                (
                    "gear_or_format",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reel",
                "verbose_name_plural": "Reels",
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_published"],
                        name="content_ree_categor_5ab2e7_idx",
                    ),
                    models.Index(fields=["slug"], name="content_ree_slug_8426f6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="content.aboutprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("url", models.URLField(max_length=500)),
                ("handle", models.CharField(blank=True, default="", max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="content.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["sort_order", "platform"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Public ID matching frontend deep link",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cached category label matching frontend item.category",
                        max_length=100,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(help_text="Maps to frontend 'src'", max_length=500),
                ),
                (
                    "cloudinary_public_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("alt", models.CharField(max_length=255)),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[
                            ("landscape", "Landscape"),
                            ("portrait", "Portrait"),
                            ("wide", "Wide"),
                            ("square", "Square"),
                        ],
                        default="landscape",
                        max_length=20,
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=255)),
                (
                    "client_or_context",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this work on the home page"
                    ),
                ),
                ("featured_order", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_items",
                        to="content.portfoliocategory",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_items",
                        to="content.discipline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Item",
                "verbose_name_plural": "Portfolio Items",
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["discipline", "is_published"],
                        name="content_por_discipl_d5fe57_idx",
                    ),
                    models.Index(fields=["slug"], name="content_por_slug_ff8a4c_idx"),
                    models.Index(
                        fields=["is_featured", "featured_order"],
                        name="content_por_is_feat_177496_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Offering id, e.g. photo-event", max_length=100
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "deliverables",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="content.servicegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Offering",
                "verbose_name_plural": "Service Offerings",
                "ordering": ["sort_order", "name"],
                "unique_together": {("group", "slug")},
            },
        ),
    ]
