# Generated by Django 5.1.15 on 2026-10-09 17:37

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalpost",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="aboutprofile",
            name="portrait_src",
            field=models.URLField(
                default="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1600&q=85",
                max_length=500,
                validators=[apps.content.models.validate_https_url],
            ),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="hero_image_url",
            field=models.URLField(
                max_length=500, validators=[apps.content.models.validate_https_url]
            ),
        ),
        migrations.AlterField(
            model_name="journalpost",
            name="cover_image_url",
            field=models.URLField(
                max_length=500, validators=[apps.content.models.validate_https_url]
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="image_url",
            field=models.URLField(
                help_text="Maps to frontend 'src'",
                max_length=500,
                validators=[apps.content.models.validate_https_url],
            ),
        ),
        migrations.AlterField(
            model_name="reel",
            name="poster_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Custom poster image URL (HTTPS). If left blank, defaults to YouTube HQ thumbnail.",
                max_length=500,
                validators=[apps.content.models.validate_https_url],
            ),
        ),
        migrations.AlterField(
            model_name="reel",
            name="video_src",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Direct MP4 video URL for legacy/HTML5 fallback",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="hero_image_url",
            field=models.URLField(
                max_length=500, validators=[apps.content.models.validate_https_url]
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_side_image_url",
            field=models.URLField(
                blank=True,
                default="https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1600&q=85",
                max_length=500,
                validators=[apps.content.models.validate_https_url],
            ),
        ),
    ]
